init app
Nyorikenoichi/workout-app pull request #2
Opened 2022-01-14 18:15 UTC by Nyorikenoichi

2022-01-15 15:21 UTC, M-fil requested changes

2022-01-15 15:21 UTC, M-fil commented on .eslintignore
> +dist
1-е, папка pages должна быть в src.

То есть в src у тебя будет pages и core.

2022-01-15 15:21 UTC, M-fil commented on .eslintignore
> +dist
Также вот примерная структура внутри папки pages
<img width="268" alt="Screenshot 2022-01-15 at 5 45 42 PM" src="https://user-images.githubusercontent.com/56369004/149625970-7980740a-368d-44b6-b5f2-3480caf30359.png">

2022-01-15 15:21 UTC, M-fil commented on .huskyrc.json
> +  "hooks": {
Макс, твой pre-commit не работает. Попробуй добавить в tsx файл console.log и затем сделай коммит. Твой pre-commit не сработает и пропустит ошибку с console.log.

В общем, рекомендую сделать инициализацию husky через .husky файл

2022-01-15 15:21 UTC, M-fil commented on package.json
> +    "*": [
Лучше ставь следующее для lint-staged:

```
    "!(.eslintrc).{ts,tsx}": ["npx eslint --fix --max-warnings 0"],
    "*.{ts,tsx,html,css,json,md}": ["prettier --write"]
```

2022-01-15 15:21 UTC, M-fil commented on src/core/components/App.tsx
> +              element={<p>{t('exerciseTitle')}</p>}
Лучше сразу создай отдельные компоненты для твоего MainRoutes.exercise и для страницы с ошибкой

2022-01-15 15:21 UTC, M-fil commented on src/core/components/reducer.tsx
> +    case 'increment':
'increment' и 'decrement' стоит создавать как значения в enum. Рекомендую сделать src/core/store/action-types папку и делать там enum-ы для типов определенных редьюсеров.

Также этот файл src/core/components/reducer.tsx лучше перенести в src/core/store/reducers

2022-01-15 15:21 UTC, M-fil commented on src/core/components/reducer.tsx
> +    case 'increment':
Вот тебе пример, как можно делать action-types через enum:

https://github.com/ural1493/Innowise-Lab-Internship-Level-3-Google-Speech/blob/dev/src/core/redux/types/auth/login.ts

2022-01-15 15:21 UTC, M-fil commented on src/core/pages/authentication.tsx
> +  const onIncrement = () => dispatch({ type: 'increment' });
Лучше делай action-функции вместо того, чтобы самом указывать в компоненте { type: 'increment' }.

Рекомендую пихать эти функции в src/core/store/actions

Вот тебе пример таких функций: https://github.com/Pyroti/Innowise-Lab-Internship-Level-1-March-Trello/blob/main/src/core/redux/action-creators/auth/googleSignInAction.ts

2022-01-15 15:21 UTC, M-fil commented on src/index.tsx
> +// import { app, database } from './core/firebase/firebaseInit';
Убираем комментарии

2022-01-17 13:10 UTC, M-fil approved these changes

2022-01-17 13:10 UTC, M-fil commented on src/core/store/action-types/globalStateActionTypes.ts
> +  inc = 'increment',
Лучше называй ключи полным именем и с большой буквы `Increment`

2022-01-17 13:10 UTC, M-fil commented on .eslintrc.json
> +{
Файл App.tsx лучше вынеси в src

2022-01-17 13:10 UTC, M-fil commented on .eslintrc.json
> +  "extends": [
Макс, твой pre-commit не работает. Я сделал комит и он пропустил мою ошибку eslint. Поэтому это нужно исправить.
<img width="1025" alt="Screenshot 2022-01-17 at 4 07 34 PM" src="https://user-images.githubusercontent.com/56369004/149774699-ec8e9ed8-9bd6-45b4-8de9-bf620fc95aba.png">

2022-01-17 13:10 UTC, M-fil commented on src/core/store/actions/globalStateActions.ts
> +export const globalStateInc = (): GlobalStateAction => ({
Ну и функции стоит называть конечно так, чтобы был в функции глагол. У тебя пока что одни существительные и прилагательные.

Я бы назвал `incrementAction`. Я обычно добавляю слово action к названию action-функций

2022-01-17 13:30 UTC, Nyorikenoichi commented on src/core/store/actions/globalStateActions.ts
> +export const globalStateInc = (): GlobalStateAction => ({
increment - это вроде и есть глагол. хотя перевести по разному можно

2022-01-17 14:09 UTC, merged