Feature/exercise page
Nyorikenoichi/workout-app pull request #6
Opened 2022-02-10 23:47 UTC by Nyorikenoichi

2022-02-13 13:30 UTC, M-fil requested changes

2022-02-13 13:30 UTC, M-fil commented on src/App.tsx
> +import Workout from './pages/workout/workout';
Сразу выделю ощутимые проблемы в UI.

1. Весь контент конкретного упражнения должен помещаться на все странице и он не должен скролиться.
<img width="1440" alt="Screenshot 2022-02-13 at 2 51 09 PM" src="https://user-images.githubusercontent.com/56369004/153751766-f7bfa28a-1382-4c81-babb-0a2e9068e234.png">

2. Когда я нажимаю "Pause", то стоит заменять эту кнопку на "Resume", потому что после нажатия есть ощущение как-будто бы ничего не произошло.

3. Почему когда я возвращаюсь на главную страницу, то у меня снова идет получение данных и появляется лоудер. Ведь тренировки должны загружаться при первом запуске. Нет смысла это делать при каждом переходе на главную страницу.

<img width="1440" alt="Screenshot 2022-02-13 at 2 55 08 PM" src="https://user-images.githubusercontent.com/56369004/153754246-8bea0812-4b53-4a16-a717-c84090a25b11.png">

4. Почему такое большое расстояние между упражнениями и header-ом:

<img width="1440" alt="Screenshot 2022-02-13 at 3 58 56 PM" src="https://user-images.githubusercontent.com/56369004/153754297-d2ab2167-5b28-407c-81a1-cbdd76fe92f8.png">

5. Также кнопка pause должна ведь располагаться в этом блоке. Стоит сразу делать более менее правильный UI:

<img width="835" alt="Screenshot 2022-02-13 at 4 01 22 PM" src="https://user-images.githubusercontent.com/56369004/153754415-09281d72-8399-464f-a1eb-83526d3a287d.png">

6. Сделай UI айтема тренировки как здесь:
<img width="711" alt="Screenshot 2022-02-13 at 4 03 48 PM" src="https://user-images.githubusercontent.com/56369004/153754472-427c99d3-094f-4a9a-877b-74324f764bdc.png">
Также поудаляй некоторые лишние элементы. Например, как точка с запятой
<img width="346" alt="Screenshot 2022-02-13 at 2 54 25 PM" src="https://user-images.githubusercontent.com/56369004/153754488-7082e983-6fdd-4a25-983a-e5597d74a812.png">

7. Кнопка Start Wokrout должна быть других стилей и в абсолютном позиционировании:
<img width="786" alt="Screenshot 2022-02-13 at 4 05 39 PM" src="https://user-images.githubusercontent.com/56369004/153754540-c1ad3ea8-d4f9-47dc-9993-ef213fb577b5.png">

8. Когда у тебя отсчет доходит до 3, 2, 1, то нужно добавлять специальный звук отсчета, чтобы юзер понимал, что время заканчивается. Также когда таймер закончился (достиг нуля), то также стоит добавить какой-либо звук, возможно звук сирены


<img width="1440" alt="Screenshot 2022-02-13 at 4 07 08 PM" src="https://user-images.githubusercontent.com/56369004/153754613-524eb14b-6b9d-42a8-bfb9-542b018a9682.png">

9. Ну и девятое конечно же. Сделай стили такие же как в макете Figma: https://www.figma.com/file/KiCMnFPh0I2cEHbWnI2fzz/Excercises-of-a-workout?node-id=0%3A1

Намного легче сначала делать более менее правильные стили, а затем их немного подправлять, чем сначала делать полностью другие стили, а затем их полностью переписывать

2022-02-13 13:30 UTC, M-fil commented on src/core/store/reducers/globalStateReducer.tsx
> +    case GlobalStateActionTypes.SetCurrentExerciseGroup:
Плохо сетать именно так:

```
        ...state,
        ...action.payload,
```

Так совсем непонятно, что у тебя изменяется в стейте. Рекомендую делать так:

```
        ...state,
        currentExerciseGroup: { ...state.currentExerciseGroup, ...action.payload.updatedCurrentExerciseGroup },
```

Это если обновлять его. Если просто сетать, то можно так:
```
...state,
currentExerciseGroup: action.payload.currentExerciseGroup,
```

Это очень важно, поэтому настоятельно рекомендую переписать это. Также сделай то же самое и для других твоих case-ов в этом reducer-е

2022-02-13 13:30 UTC, M-fil commented on src/core/store/thunk/firestore.tsx
> +export const getInitialDataAction =
Похвально! Очень классно разделил все thunk на файлы и грамотно реализовал логику этих функций.

2022-02-13 13:30 UTC, M-fil commented on src/core/style/mainTheme.tsx
> +    workoutSpinner: string;
Называй более конкретно цвета. По название workoutSpinner не понятно, для чего этот цвет. Для background, color, border-color? Нужно уточнять. Более правильно было бы workoutSpinnerBacgroundColor, если конечно этот цвет используется как background-color

2022-02-13 13:30 UTC, M-fil commented on src/core/style/mainTheme.tsx
> +    workoutSpinner: string;
То же самое исправь и для:
```
    workoutSpinnerSecondary: string;
    workoutSpinnerPaused: string;
```

2022-02-13 13:30 UTC, M-fil commented on src/pages/excercise/excercises.tsx
> +        <Button variant="contained">Start Exercise</Button>
Start Exercise - выносим в react-i18next

2022-02-13 13:30 UTC, M-fil commented on src/pages/excercise/excercises.tsx
> +        <ListItem key={item.id}>
Лучше вынести в отдельную компоненту:
```
      return (
        <ListItem key={item.id}>
          <Icon>
            <img src={item.photo} height={25} width={25} alt="" />
          </Icon>
          <ListItemText
            primary={item.title}
            secondary={`${item.duration} sec`}
          />
          ;
        </ListItem>
```

2022-02-13 13:30 UTC, M-fil commented on src/pages/excercise/excercises.tsx
> +export default function Exercises() {
Также еще один момент. Если у компонента нету props-ов, либо все пропсы конкретного компонента являются примитивами, то данный компонент нужно обернуть в React.memo. Просмотри все свои компоненты и оберни их в React.memo, если это нужно

2022-02-13 13:30 UTC, M-fil commented on src/pages/main/components/workoutCard.tsx
> +  const setCurrentExercises = () => {
Функции для событий я рекомендую называть через `on`. То есть `onSetCurrentExercises`

2022-02-13 13:30 UTC, M-fil commented on src/pages/main/main.tsx
> +  function renderCards(cards: ExerciseGroup[]): JSX.Element[] {
Внутри компонента лучше делай стрелочные функции

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/finishTraining.tsx
> +        Nice job. You’re done. Here’s the workout summary.
Текст для react-i18next

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/progress.tsx
> +            value={100 - progressValue}
Магическое число: 100 - progressValue

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/progress.tsx
> +            size={128}
Данные параметры рекомендую вынести в константу на уровне компонента:

            size={128}
            thickness={3}

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/progress.tsx
> +        {`${displayValue < 10 ? '0' : ''}${displayValue}`}
10 - магическое число

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/progress.tsx
> +        {`${displayValue < 10 ? '0' : ''}${displayValue}`}
А вообще лучше создать отдельную вспомогательную функцию, которая будет работать с этой логикой:

```
{`${displayValue < 10 ? '0' : ''}${displayValue}`}
```

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +  const [exerciseCounter, setCounter] = useState(5);
5 - магическое число

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +      setCounter(5);
5 - магическое число

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +      setCounter(5);
5 - магическое число

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +      100 -
100 и 5 - магические числа

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +    }, 1000);
1000 стоит вынести в константу

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/workout.tsx
> +  const exercisesCount = state.currentExerciseGroup?.exercises.length as number;
Вообще в этом компоненте слишком много логики. А в чистом коде нам стоит отделять UI от логики. В React-е это можно сделать через кастомные хуки. Рекомендую вынести почти всю твою этого компонента в кастомный хук

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/finishTraining.tsx
> +      <Typography>{`Minutes: ${Math.round(time / 60)}`}</Typography>
Стоит вынести в helper-фукнцию (вспомогательную функцию)

Math.round(time / 60)}

Также 60 - магическое число

2022-02-13 13:30 UTC, M-fil commented on src/pages/workout/components/finishTraining.tsx
> +      <Typography variant="h2">Workout Complete!</Typography>
Текст для react-i18next

2022-02-13 13:30 UTC, M-fil commented on src/App.tsx
> +                <Route path={MainRoutes.workout} element={<Workout />} />
А зачем эта картинка [ссылка](https://github.com/Nyorikenoichi/workout-app/pull/6/files?short_path=c0361d0#diff-c0361d0dfbc39a96a07bc8318a4c27d8fad4bef634962268673274f6e9923f96)? Она точна нужна?

2022-02-17 11:24 UTC, M-fil requested changes
Еще пару изменений и можно будет Аппрувать

2022-02-17 11:24 UTC, M-fil commented on package.json
> +    "@mui/icons-material": "^5.4.1",
Поплыла верстка в header и появился горизонтальный скрол:
<img width="1440" alt="Screenshot 2022-02-17 at 1 58 25 PM" src="https://user-images.githubusercontent.com/56369004/154468521-106b9f37-750b-423c-854b-ba73ab02ad82.png">

2022-02-17 11:24 UTC, M-fil commented on src/core/api/statistics.ts
> +import { Statistics } from '../interfaces/statistics';
Не исправил это замечание про React.memo:

https://github.com/Nyorikenoichi/workout-app/pull/6/files/3c23b9140bccef76481b76ba2acae98b786bb3db#diff-159b88fc9eb3f83292a82c92d7f31cb825d18af2220f9c232807b132a130bc3e

2022-02-17 11:24 UTC, M-fil commented on src/core/api/statistics.ts
> +  return docSnap.data() as Statistics;
Не исправил мои замечания:

```
      <ProgressValue variant="caption">
        {`${displayValue < 10 ? '0' : ''}${displayValue}`}
      </ProgressValue>
```

<img width="813" alt="Screenshot 2022-02-17 at 2 10 26 PM" src="https://user-images.githubusercontent.com/56369004/154469590-6d700b44-3abc-4cd6-8ceb-6581295e7cbe.png">

2022-02-17 11:24 UTC, M-fil commented on src/core/components/header/components/logoutButton.ts
> +import styled from 'styled-components';
По поводу этого файла: https://github.com/Nyorikenoichi/workout-app/pull/6/files/3c23b9140bccef76481b76ba2acae98b786bb3db#diff-1b41d688d6502425b0efd855489a008a28a1abd29a68922740a342622672ec0b

1. Такие константы, как:
```
  const preparingDuration = 5;
  const oneSecond = 1000;
```

Рекомендую выносить за компоненту и хранить в том же файле, где храниться компонента.

2. oneSecond - плохое название. Нужно больше конкретики. Например, если это время, после которого прячется лоудер, то назвать его можно TimeoutToHideLoader

2022-02-17 11:24 UTC, M-fil commented on src/core/components/header/components/logoutButton.ts
> +import styled from 'styled-components';
3. Также в начальный стейт подставь свой preparingDuration вместо 5

  const [exerciseCounter, setCounter] = useState(5);

2022-02-17 11:24 UTC, M-fil commented on src/core/components/header/components/logoutButton.ts
> +export const LogoutButton = styled(Button)`
Про этот файл: src/pages/workout/workout.tsx

1. Данную функцию лучше вынести в хук useExerciseTimer:
```
  const convertCounterToPercent = () => {
    return (
      100 -
      (100 * exerciseCounter) /
        (isPreparing
          ? preparingDuration
          : (currentExercise?.duration as number))
    );
  };
```

2. 100 - магическое число. Так и не пофиксил с предыдущего ревью

2022-02-17 11:24 UTC, M-fil commented on src/core/constants/exerciseGroupNames.ts
> +  warmUp = 'Warm up',
Лучше не делать пробелы в названиях идентификаторов. Вместо них лучше ставь - или _

2022-02-17 11:24 UTC, M-fil commented on src/core/constants/exerciseGroupNames.ts
> +  warmUp = 'Warm up',
'Warm up'

2022-02-17 11:24 UTC, M-fil commented on src/core/hooks/useExerciseTimer.ts
> +import { RefObject, useEffect, useRef, useState } from 'react';
1. Данную функцию лучше вынести в вспомогательные функции. Можно поместить ее в src/core/helpers/date.ts

```
  const timeToMinutes = (seconds: number): number => {
    const oneMinute = 60;
    return Math.round(seconds / oneMinute);
  };
```

2. Также название oneMinute не подойдет. По названию oneMinute нельзя понять, что хранит данная переменная. Это количество минут в одном часе? Или количество секунд в минуте? Не понятно, поэтому нужно больше конкретики

2022-02-18 16:00 UTC, Nyorikenoichi commented on src/core/constants/exerciseGroupNames.ts
> +  warmUp = 'Warm up',
поставил такое имя, потому что от api именно в таком формате приходит. по другому будет не очень удобно сравнивать с тем, что приходит из api

2022-02-21 08:24 UTC, M-fil approved these changes

2022-02-21 08:24 UTC, M-fil commented on src/pages/workout/workout.tsx
> +    const fullProgress = 100;
Про кастомный хук useExerciseTimer. У тебя возвращающий тип - это массив:
```
[
  Exercise | undefined,
  number,
  boolean,
  () => void,
  boolean,
  () => void,
  () => void,
  number,
  () => number,
  number,
  boolean,
  RefObject<HTMLVideoElement>
]
```

Когда столько много параметров, то лучше возвращать объект. С массивом можно делать, когда у тебя максимум 2 параметра возвращаются из функции.

Поэтому переделай под объект

2022-02-21 10:36 UTC, merged